/* =========================================================
   GUIDEON Schema
   PostgreSQL 16+ / PostGIS / pgvector / pg_trgm
   ========================================================= */

-- Extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- updated_at auto trigger function
CREATE OR REPLACE FUNCTION guideon_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ENUM types
DO $$ BEGIN
  CREATE TYPE zone_source_enum AS ENUM ('AUTO', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE info_type_enum AS ENUM ('NOTICE', 'HOURS', 'MENU_SIMPLE', 'PRICE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE doc_status_enum AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE actor_type_enum AS ENUM ('ADMIN', 'SYSTEM', 'DEVICE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE action_type_enum AS ENUM ('CREATE', 'UPDATE', 'DELETE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE admin_role_enum AS ENUM ('PLATFORM_ADMIN', 'SITE_ADMIN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE admin_invite_status_enum AS ENUM ('PENDING', 'USED', 'EXPIRED', 'REVOKED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- tb_site
CREATE TABLE IF NOT EXISTS tb_site (
  site_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE TRIGGER trg_site_updated_at
BEFORE UPDATE ON tb_site
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_admin
CREATE TABLE IF NOT EXISTS tb_admin (
  admin_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  role           admin_role_enum NOT NULL DEFAULT 'SITE_ADMIN',
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at  TIMESTAMPTZ NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_admin_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_admin_role_active ON tb_admin (role, is_active);

CREATE OR REPLACE TRIGGER trg_admin_updated_at
BEFORE UPDATE ON tb_admin
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_admin_site
CREATE TABLE IF NOT EXISTS tb_admin_site (
  admin_id   BIGINT NOT NULL REFERENCES tb_admin(admin_id) ON DELETE CASCADE,
  site_id    BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (admin_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_site_site_id ON tb_admin_site (site_id);

-- tb_admin_invite
CREATE TABLE IF NOT EXISTS tb_admin_invite (
  invite_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id             BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  email               VARCHAR(255) NOT NULL,
  role                admin_role_enum NOT NULL DEFAULT 'SITE_ADMIN',
  token_hash          CHAR(64) NOT NULL,
  status              admin_invite_status_enum NOT NULL DEFAULT 'PENDING',
  expires_at          TIMESTAMPTZ NOT NULL,
  used_at             TIMESTAMPTZ NULL,
  created_by_admin_id BIGINT NULL REFERENCES tb_admin(admin_id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_invite_token_hash UNIQUE (token_hash)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_invite_site_email_pending
ON tb_admin_invite (site_id, email)
WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_invite_site_status ON tb_admin_invite (site_id, status);
CREATE INDEX IF NOT EXISTS idx_invite_expires_at ON tb_admin_invite (expires_at);

CREATE OR REPLACE TRIGGER trg_admin_invite_updated_at
BEFORE UPDATE ON tb_admin_invite
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_zone
CREATE TABLE IF NOT EXISTS tb_zone (
  zone_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id        BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  name           VARCHAR(50) NOT NULL,
  code           VARCHAR(50) NOT NULL,
  zone_type      VARCHAR(10) NOT NULL,
  level          SMALLINT GENERATED ALWAYS AS (
    CASE zone_type
      WHEN 'INNER' THEN 1
      WHEN 'SUB'   THEN 2
    END
  ) STORED,
  parent_zone_id BIGINT NULL REFERENCES tb_zone(zone_id) ON DELETE SET NULL,
  area_geometry  geometry(Polygon, 4326) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_zone_code UNIQUE (site_id, code),
  CONSTRAINT uk_zone_id_site UNIQUE (zone_id, site_id),
  CONSTRAINT ck_zone_type CHECK (zone_type IN ('INNER', 'SUB'))
);

CREATE INDEX IF NOT EXISTS idx_zone_geom_gist ON tb_zone USING GIST (area_geometry);
CREATE INDEX IF NOT EXISTS idx_zone_site_type ON tb_zone (site_id, zone_type, level);
CREATE INDEX IF NOT EXISTS idx_zone_parent ON tb_zone (parent_zone_id);

CREATE OR REPLACE TRIGGER trg_zone_updated_at
BEFORE UPDATE ON tb_zone
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

ALTER TABLE tb_zone DROP CONSTRAINT IF EXISTS ck_zone_type_parent_consistency;
ALTER TABLE tb_zone
ADD CONSTRAINT ck_zone_type_parent_consistency
CHECK (
  (zone_type = 'INNER' AND parent_zone_id IS NULL)
  OR
  (zone_type = 'SUB'   AND parent_zone_id IS NOT NULL)
);

-- tb_place
CREATE TABLE IF NOT EXISTS tb_place (
  place_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  zone_id      BIGINT NULL,
  zone_source  zone_source_enum NOT NULL DEFAULT 'AUTO',
  name         VARCHAR(100) NOT NULL,
  name_json    JSONB NULL,
  category     VARCHAR(50) NOT NULL,
  location     geography(Point, 4326) NOT NULL,
  description  TEXT NULL,
  image_url    VARCHAR(500) NULL,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_place_id_site UNIQUE (place_id, site_id),
  CONSTRAINT fk_place_zone_site
    FOREIGN KEY (zone_id, site_id)
    REFERENCES tb_zone(zone_id, site_id)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_place_loc_gist ON tb_place USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_place_filter ON tb_place (site_id, category, is_active);
CREATE INDEX IF NOT EXISTS idx_place_site_active ON tb_place (site_id, is_active);

CREATE OR REPLACE TRIGGER trg_place_updated_at
BEFORE UPDATE ON tb_place
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_device
CREATE TABLE IF NOT EXISTS tb_device (
  device_id      VARCHAR(50) PRIMARY KEY,
  auth_token_hash CHAR(64) NOT NULL,
  site_id         BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  zone_id         BIGINT NULL,
  zone_source     zone_source_enum NOT NULL DEFAULT 'AUTO',
  location_name   VARCHAR(100) NOT NULL,
  location        geography(Point, 4326) NOT NULL,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  last_ping       TIMESTAMPTZ NULL,
  last_auth_at    TIMESTAMPTZ NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_device_zone_site
    FOREIGN KEY (zone_id, site_id)
    REFERENCES tb_zone(zone_id, site_id)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_device_loc_gist ON tb_device USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_device_site_active ON tb_device (site_id, is_active);

CREATE OR REPLACE TRIGGER trg_device_updated_at
BEFORE UPDATE ON tb_device
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_mascot
CREATE TABLE IF NOT EXISTS tb_mascot (
  mascot_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id        BIGINT NOT NULL UNIQUE REFERENCES tb_site(site_id) ON DELETE CASCADE,
  name           VARCHAR(50) NOT NULL,
  model_id       VARCHAR(80) NOT NULL,
  default_anim   VARCHAR(50) NOT NULL DEFAULT 'IDLE_A',
  greeting_msg   VARCHAR(200) NOT NULL,
  system_prompt  TEXT NOT NULL,
  tts_voice_id   VARCHAR(50) NOT NULL,
  tts_voice_json JSONB NULL,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE TRIGGER trg_mascot_updated_at
BEFORE UPDATE ON tb_mascot
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_document
CREATE TABLE IF NOT EXISTS tb_document (
  doc_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id         BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  original_name   VARCHAR(255) NOT NULL,
  storage_url     VARCHAR(500) NOT NULL,
  file_hash       CHAR(64) NOT NULL,
  file_size       BIGINT NULL,
  chunk_size      INT NOT NULL DEFAULT 500,
  chunk_overlap   INT NOT NULL DEFAULT 50,
  embedding_model VARCHAR(100) NOT NULL DEFAULT 'text-embedding-3-small',
  status          doc_status_enum NOT NULL DEFAULT 'PENDING',
  failed_reason   TEXT NULL,
  processed_at    TIMESTAMPTZ NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_doc_hash UNIQUE (site_id, file_hash),
  CONSTRAINT uk_doc_id_site UNIQUE (doc_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_doc_site_status ON tb_document (site_id, status);

CREATE OR REPLACE TRIGGER trg_document_updated_at
BEFORE UPDATE ON tb_document
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_doc_chunk
CREATE TABLE IF NOT EXISTS tb_doc_chunk (
  chunk_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      BIGINT NOT NULL,
  doc_id       BIGINT NOT NULL,
  chunk_index  INT NOT NULL,
  content      TEXT NOT NULL,
  metadata     JSONB NULL,
  embedding    vector(1536) NULL,
  content_tsv  TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(content, ''))
  ) STORED,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chunk_doc_site
    FOREIGN KEY (doc_id, site_id)
    REFERENCES tb_document(doc_id, site_id)
    ON DELETE CASCADE,
  CONSTRAINT uk_chunk_order UNIQUE (doc_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_chunk_embedding_hnsw
ON tb_doc_chunk USING hnsw (embedding vector_cosine_ops)
WHERE embedding IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_chunk_tsv_gin
ON tb_doc_chunk USING GIN (content_tsv);

CREATE INDEX IF NOT EXISTS idx_chunk_content_trgm
ON tb_doc_chunk USING GIN (content gin_trgm_ops);

-- tb_daily_info
CREATE TABLE IF NOT EXISTS tb_daily_info (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id     BIGINT NOT NULL,
  place_id    BIGINT NOT NULL,
  target_date DATE NOT NULL,
  info_type   info_type_enum NOT NULL,
  content     TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_daily_place_site
    FOREIGN KEY (place_id, site_id)
    REFERENCES tb_place(place_id, site_id)
    ON DELETE CASCADE,
  CONSTRAINT uk_daily UNIQUE (place_id, target_date, info_type)
);

CREATE INDEX IF NOT EXISTS idx_daily_site_date ON tb_daily_info (site_id, target_date);

CREATE OR REPLACE TRIGGER trg_daily_updated_at
BEFORE UPDATE ON tb_daily_info
FOR EACH ROW EXECUTE FUNCTION guideon_set_updated_at();

-- tb_audit_log
CREATE TABLE IF NOT EXISTS tb_audit_log (
  log_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      BIGINT NOT NULL REFERENCES tb_site(site_id) ON DELETE CASCADE,
  actor_type   actor_type_enum NOT NULL,
  actor_id     VARCHAR(50) NOT NULL,
  target_table VARCHAR(50) NOT NULL,
  target_pk    VARCHAR(64) NOT NULL,
  action_type  action_type_enum NOT NULL,
  changes_json JSONB NULL,
  ip_address   VARCHAR(45) NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_search ON tb_audit_log (site_id, target_table, created_at);
